print('HelloWorld')
print("Day1 - Python print function")
print("The function is declaed like this :")
print("'What to print'")
print("Hello!\nHello!\nHello!")
print("Hello" + " Charles")
print("Day 1 - String Manipulation")
print('String Concatenation is done with the "'+"+"+'" sign.')
print('e.g. print("Hello " + "world")')
print("New lines can be created with a backslash and n.")
print("Day 1 - String Manipulation")
print('String Concatenation is done with the "+" sign.')
print('e.g. print("Hello " + "world")')
print("New lines can be created with a backslash and n.")
